language: node_js
node_js:
  - 16.14
branches:
  only:
  - main

before_script:
  - npm install -g @angular/cli

script:
  - npm run test:cov
  - npm run test:up
  - ng build barberapp --configuration production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/barberapp
  on:
    branch: main
